name: Update Supabase Data

on:
  schedule:
    # 22:00 UTC (Sunday) = 06:00 AM Malaysia (Monday)
    - cron: '0 22 * * 0' # Runs every Monday at midnight UTC
  workflow_dispatch: # Allows manual trigger button

jobs:
  update-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install pandas sqlalchemy psycopg2-binary toml

      - name: Run Publisher Script
        env:
          DB_PASS: ${{ secrets.DB_PASS }}
          # UPDATED HOST: Note the 'aws-1' instead of 'aws-0'
          DB_HOST: "aws-1-ap-southeast-1.pooler.supabase.com"
          DB_PORT: "6543"
          DB_NAME: "postgres"
          # User from your string
          DB_USER: "postgres.fvrzvqamufqfjqufxfqp"
        run: python publish_data.py
